### ISSUE TITLE
E6: Visibility

### ISSUE THREAD

**Issue by danielmiehle** [eclipse/tractusx#19]
As a traceability app user, I want that the one-up-one-down visibility rule is kept at all times ensuring compliance.

- [x] one-up-one-down visibility concept enforced at all times.

**Comment by lorenzoisoldi** [comment]
This is the standard view "one up and one down" - e.g. Tier 3 Company can see all his customers and all his direct sourced suppliers.
Maybe in a later point of time it will be possible to make the vertical supply chain completely visible (special cases – not specified currently)
