### ISSUE TITLE
UI/UX Flow of a special  QualityType "Safety Relevant"

### ISSUE THREAD

**Issue by lorenzoisoldi** [eclipse/tractusx#31]
As a supplier of sub-components I want to Raise a quality alert of quality QualityType "Safety Relevant" . 
The alert should pass through supplier level to the OEM. 

This flow should be simulated as a pure showCase.

_Originally posted by @lorenzoisoldi in https://github.com/eclipse/tractusx/issues/17#issuecomment-839767647_

**Comment by lorenzoisoldi** [comment]
This issue should not be implemented neither in service nor in the apps. In first approach , this is as mentioned a pure showCase.

**Comment by danielmiehle** [comment]
Done.
