### ISSUE TITLE
E4: App Store UI

### ISSUE THREAD

**Issue by danielmiehle** [eclipse/tractusx#35]
As a portal user, I want a portal user interface, so that I can navigate through the tractus-x network.

- [ ] Top navigation consists of 5 buttons (Dashboard, AppStore, Data Catalog, Vocabulary and Developer Hub)
- [ ] Vocabulary and Developer Hub  status is "coming soon"
- [ ] Subcategories of Dashboard is myApps, myData, myConnections (left navigation)
- [ ] myApps include business apps and data upload app
- [ ] myData includes providing and consuming data view
- [ ] myConnections include data lineage view
- [ ] myConnections: Network admins can manage / edit connections
- [ ] myConnections: Network users can only view connections
- [ ] App store landing page shows a banner with the latest news
- [ ] App store landing page shows the most popular apps

**Comment by annkmay** [comment]
do we have subcategories for my Apps, my Data, my Connections or is it the last level?

**Comment by chrisjones262** [comment]
consolidated into #47
