### ISSUE TITLE
Portal Detail: Register Now - Create Admin Account

### ISSUE THREAD

**Issue by chrisjones262** [eclipse/tractusx#44]
As an admin of a company, I want to create an admin account, so that I can create or connect my organization on tractus-x and add users.

**Submit Admit Account Application** 
Enter first and last name, e-mail, password and accept terms and conditions.  
Show "register" button to submit registration.
Show "cancel" button to terminate the registration process.
Send e-mail to admin in order to verify its e-mail adress.

Note: Data entered is captured for future reuse (Cache or database).  

**Confirm Admin Account Application**
Show notification that admin account was created and the user needs to verify its e-mail.
Verify e-mail via link in the e-mail.

![image](https://user-images.githubusercontent.com/29955508/119979135-d26b4600-bfba-11eb-8bce-5bd315fe9b51.png)
![image](https://user-images.githubusercontent.com/29955508/119979460-49084380-bfbb-11eb-8db3-95608a734a36.png)

**Comment by danielmiehle** [comment]
Done.
