### ISSUE TITLE
Portal Detail:  App Store

### ISSUE THREAD

**Issue by chrisjones262** [eclipse/tractusx#47]
As a user, I want an app store navigation, so that I can navigate through the tractus-x platform and business applications.

Top navigation consists of 5 buttons: 

- AppStore 
- Dashboard (see #53)
- Data Catalog (tbd.)
- Vocabulary ("coming soon" page)
- Developer Hub ("coming soon" page)

App store landing page shows a banner with the latest news
App store landing page shows the most popular business apps

![image](https://user-images.githubusercontent.com/29955508/119989110-18c6a200-bfc7-11eb-918d-95b825fe514c.png)

**Comment by chrisjones262** [comment]
@danielmiehle  should you mention that clicking on PartChain will take the user to <PartChain URL>?

**Comment by danielmiehle** [comment]
@chrisjones262: Yes. Clicking on the PartChain Tile will take the user the PartChain System using the SSO. UI screens for PartChain will be provided.
